In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load Databases
fd = 'D:\Descargas\Proyecto Final\Resources'
appearances = f'{fd}/appearances.csv'
clubs = f'{fd}/clubs.csv'
competitions = f'{fd}/competitions.csv'
games = f'{fd}/games.csv'
players = f'{fd}/players.csv'

In [3]:
appearances_df = pd.read_csv(appearances)
appearances_df.head()

,player_id,game_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards
0,410184,2602706,2602706_410184,UKR1,6994,0,0,45,0,0
1,84938,2581152,2581152_84938,L1,3,0,0,90,0,0
2,84938,2581178,2581178_84938,L1,3,0,0,90,0,0
3,84938,2581188,2581188_84938,L1,3,0,0,90,0,0
4,84938,2581196,2581196_84938,L1,3,0,0,90,0,0

In [4]:
clubs_df = pd.read_csv(clubs)
clubs_df.head()

,club_id,name,pretty_name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,url
0,6996,goverla-uzhgorod,Goverla Uzhgorod,UKR1,NaN,0,0.0,0,NaN,0,Avangard,10640,+-0,Vyacheslav Groznyi,https://www.transfermarkt.co.uk/goverla-uzhgor...
1,6994,metalurg-zaporizhya-bis-2016-,Metalurg Zaporizhya Bis 2016,UKR1,NaN,0,0.0,0,NaN,0,ZAZ Stadion,15000,+-0,Anatoliy Chantsev,https://www.transfermarkt.co.uk/metalurg-zapor...
2,7185,panthrakikos-komotini,Panthrakikos Komotini,GR1,23.0,5,26.3,3,60.0,1,Stadio Komotinis OPAP,5601,+-0,Jos√© Manuel Roca,https://www.transfermarkt.co.uk/panthrakikos-k...
3,3216,mersin-idmanyurdu,Mersin Idmanyurdu,TR1,NaN,0,0.0,0,NaN,0,Mersin Stadyumu,25497,+-0,Mesut Bakkal,https://www.transfermarkt.co.uk/mersin-idmanyu...
4,28956,ael-kalloni,Ael Kalloni,GR1,NaN,0,0.0,0,NaN,0,Stadio Mytilinis,4000,+-0,Thalis Theodoridis,https://www.transfermarkt.co.uk/ael-kalloni/st...

In [5]:
competitions_df = pd.read_csv(competitions)
competitions_df.head()

,competition_id,name,type,country_id,country_name,domestic_league_code,confederation,url
0,L1,bundesliga,first_tier,40,Germany,L1,europa,https://www.transfermarkt.co.uk/bundesliga/sta...
1,DFB,dfb-pokal,domestic_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfb-pokal/star...
2,DFL,dfl-supercup,domestic_super_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfl-supercup/s...
3,NL1,eredivisie,first_tier,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/eredivisie/sta...
4,NLP,toto-knvb-beker,domestic_cup,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/toto-knvb-beke...

In [6]:
games_df = pd.read_csv(games)
games_df.head()

,game_id,competition_code,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,stadium,attendance,url
0,2581147,L1,2015,1. Matchday,2015-08-14,27,41,5,0,1.0,18.0,Allianz Arena,75024.0,https://www.transfermarkt.co.uk/bayern-munich_...
1,2576512,DFL,2015,Final,2015-08-01,82,27,6,5,NaN,NaN,Volkswagen Arena,30000.0,https://www.transfermarkt.co.uk/spielbericht/i...
2,2581181,L1,2015,2. Matchday,2015-08-22,533,27,1,2,16.0,2.0,PreZero Arena,30150.0,https://www.transfermarkt.co.uk/tsg-1899-hoffe...
3,2581179,L1,2015,2. Matchday,2015-08-22,42,15,0,1,13.0,3.0,HDI-Arena,39100.0,https://www.transfermarkt.co.uk/hannover-96_ba...
4,2581178,L1,2015,2. Matchday,2015-08-22,3,82,1,1,5.0,6.0,RheinEnergieStadion,46000.0,https://www.transfermarkt.co.uk/1-fc-koln_vfl-...

In [7]:
players_df = pd.read_csv(players)
players_df.head()

,player_id,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,height_in_cm,url
0,257767,4795,aloy-ihenacho,Aloy Ihenacho,Nigeria,Nigeria,1995-07-21,Attack,Centre-Forward,Left,182,https://www.transfermarkt.co.uk/aloy-ihenacho/...
1,320889,4795,thomas-blomeyer,Thomas Blomeyer,Germany,Germany,1996-04-24,Defender,Centre-Back,Both,191,https://www.transfermarkt.co.uk/thomas-blomeye...
2,42318,4795,konstantin-engel,Konstantin Engel,UdSSR,Kazakhstan,1988-07-27,Defender,Centre-Back,Right,179,https://www.transfermarkt.co.uk/konstantin-eng...
3,94598,4795,stefan-wannenwetsch,Stefan Wannenwetsch,Germany,Germany,NaN,Midfield,Defensive Midfield,Right,177,https://www.transfermarkt.co.uk/stefan-wannenw...
4,381921,6994,ivan-komlev,Ivan Komlev,NaN,Ukraine,1994-07-22,Defender,Centre-Back,NaN,181,https://www.transfermarkt.co.uk/ivan-komlev/pr...

In [8]:
df_list = [appearances_df, clubs_df, competitions_df, games_df, players_df]
name_list = ["appearances_df", "clubs_df", "competitions_df", "games_df", "players_df"]
for i in range(len(name_list)):
    print(f'{name_list[i].upper()} has columns with NaN values:')
    print(df_list[i].isna().sum())
    print(" ")

APPEARANCES_DF has columns with NaN values:
player_id         0
game_id           0
appearance_id     0
competition_id    0
player_club_id    0
goals             0
assists           0
minutes_played    0
yellow_cards      0
red_cards         0
dtype: int64

CLUBS_DF has columns with NaN values:
club_id                     0
name                        0
pretty_name                 0
domestic_competition_id     0
total_market_value         18
squad_size                  0
average_age                 0
foreigners_number           0
foreigners_percentage      27
national_team_players       0
stadium_name                0
stadium_seats               0
net_transfer_record         0
coach_name                  0
url                         0
dtype: int64

COMPETITIONS_DF has columns with NaN values:
competition_id          0
name                    0
type                    0
country_id              0
country_name            7
domestic_league_code    7
confederation           0
url                     0
dtype: int64

GAMES_DF has columns with NaN values:
game_id                   0
competition_code          0
season                    0
round                     0
date                      0
home_club_id              0
away_club_id              0
home_club_goals           0
away_club_goals           0
home_club_position    10429
away_club_position    10430
stadium                  93
attendance             7514
url                       0
dtype: int64

PLAYERS_DF has columns with NaN values:
player_id                    0
current_club_id              0
name                         0
pretty_name                  0
country_of_birth          1502
country_of_citizenship       0
date_of_birth               21
position                     0
sub_position                 0
foot                      1661
height_in_cm                 0
url                          0
dtype: int64

In [9]:
players_df.describe()

           player_id  current_club_id  height_in_cm
count   20626.000000     20626.000000  20626.000000
mean   289222.910889      4145.085378    172.197227
std    203292.082994      9223.325976     42.135029
min        10.000000         3.000000      0.000000
25%    111058.750000       383.000000    176.000000
50%    265527.500000      1050.000000    182.000000
75%    422451.250000      2999.000000    187.000000
max    949337.000000     61825.000000    206.000000

In [10]:
players_df.dtypes

player_id                  int64
current_club_id            int64
name                      object
pretty_name               object
country_of_birth          object
country_of_citizenship    object
date_of_birth             object
position                  object
sub_position              object
foot                      object
height_in_cm               int64
url                       object
dtype: object

In [11]:
# Dropping NaN values from columns of interest (Appereances, Clubs and Players)
players_df.dropna()
appearances_df.dropna()
clubs_df.dropna()
games_df #2021 filtro
# Print new shape
print(appearances_df.shape)
print(players_df.shape)
print(clubs_df.shape)

(820242, 10)
(20626, 12)
(364, 15)

In [12]:
games_df

,game_id,competition_code,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,stadium,attendance,url
0,2581147,L1,2015,1. Matchday,2015-08-14,27,41,5,0,1.0,18.0,Allianz Arena,75024.0,https://www.transfermarkt.co.uk/bayern-munich_...
1,2576512,DFL,2015,Final,2015-08-01,82,27,6,5,NaN,NaN,Volkswagen Arena,30000.0,https://www.transfermarkt.co.uk/spielbericht/i...
2,2581181,L1,2015,2. Matchday,2015-08-22,533,27,1,2,16.0,2.0,PreZero Arena,30150.0,https://www.transfermarkt.co.uk/tsg-1899-hoffe...
3,2581179,L1,2015,2. Matchday,2015-08-22,42,15,0,1,13.0,3.0,HDI-Arena,39100.0,https://www.transfermarkt.co.uk/hannover-96_ba...
4,2581178,L1,2015,2. Matchday,2015-08-22,3,82,1,1,5.0,6.0,RheinEnergieStadion,46000.0,https://www.transfermarkt.co.uk/1-fc-koln_vfl-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35543,3651082,CL,2021,Group C,2021-10-19,610,16,4,0,NaN,NaN,Johan Cruijff ArenA,54029.0,https://www.transfermarkt.co.uk/spielbericht/i...
35544,3651061,CL,2021,Group A,2021-09-28,583,281,2,0,NaN,NaN,Parc des Princes,37350.0,https://www.transfermarkt.co.uk/spielbericht/i...
35545,3651035,CL,2021,Group H,2021-09-14,631,964,1,0,NaN,NaN,Stamford Bridge,39252.0,https://www.transfermarkt.co.uk/spielbericht/i...
35546,3651078,CL,2021,Group A,2021-10-19,583,23826,3,2,NaN,NaN,Parc des Princes,47359.0,https://www.transfermarkt.co.uk/spielbericht/i...
35547,3651068,CL,2021,Group D,2021-09-28,418,2481,1,2,NaN,NaN,Santiago Bernab√©u,24522.0,https://www.transfermarkt.co.uk/spielbericht/i...

In [13]:
# 2018 games are 5641
games_df[games_df["season"] == 2018].count()

game_id               5641
competition_code      5641
season                5641
round                 5641
date                  5641
home_club_id          5641
away_club_id          5641
home_club_goals       5641
away_club_goals       5641
home_club_position    3986
away_club_position    3986
stadium               5631
attendance            5305
url                   5641
dtype: int64