In [16]:
import pandas as pd
import numpy as np

In [17]:
# Load Databases
fd = 'D:\Descargas\Proyecto Final\Resources'
appearances = f'{fd}/appearances.csv'
clubs = f'{fd}/clubs.csv'
competitions = f'{fd}/competitions.csv'
games = f'{fd}/games.csv'
players = f'{fd}/players.csv'
top250 = f'{fd}/top250.csv'

In [3]:
appearances_df = pd.read_csv(appearances)
appearances_df.head()

,player_id,game_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards
0,410184,2602706,2602706_410184,UKR1,6994,0,0,45,0,0
1,84938,2581152,2581152_84938,L1,3,0,0,90,0,0
2,84938,2581178,2581178_84938,L1,3,0,0,90,0,0
3,84938,2581188,2581188_84938,L1,3,0,0,90,0,0
4,84938,2581196,2581196_84938,L1,3,0,0,90,0,0

In [4]:
clubs_df = pd.read_csv(clubs)
clubs_df.head()

,club_id,name,pretty_name,domestic_competition_id,total_market_value,squad_size,average_age,foreigners_number,foreigners_percentage,national_team_players,stadium_name,stadium_seats,net_transfer_record,coach_name,url
0,6996,goverla-uzhgorod,Goverla Uzhgorod,UKR1,NaN,0,0.0,0,NaN,0,Avangard,10640,+-0,Vyacheslav Groznyi,https://www.transfermarkt.co.uk/goverla-uzhgor...
1,6994,metalurg-zaporizhya-bis-2016-,Metalurg Zaporizhya Bis 2016,UKR1,NaN,0,0.0,0,NaN,0,ZAZ Stadion,15000,+-0,Anatoliy Chantsev,https://www.transfermarkt.co.uk/metalurg-zapor...
2,7185,panthrakikos-komotini,Panthrakikos Komotini,GR1,23.0,5,26.3,3,60.0,1,Stadio Komotinis OPAP,5601,+-0,Jos√© Manuel Roca,https://www.transfermarkt.co.uk/panthrakikos-k...
3,3216,mersin-idmanyurdu,Mersin Idmanyurdu,TR1,NaN,0,0.0,0,NaN,0,Mersin Stadyumu,25497,+-0,Mesut Bakkal,https://www.transfermarkt.co.uk/mersin-idmanyu...
4,28956,ael-kalloni,Ael Kalloni,GR1,NaN,0,0.0,0,NaN,0,Stadio Mytilinis,4000,+-0,Thalis Theodoridis,https://www.transfermarkt.co.uk/ael-kalloni/st...

In [5]:
competitions_df = pd.read_csv(competitions)
competitions_df.head()

,competition_id,name,type,country_id,country_name,domestic_league_code,confederation,url
0,L1,bundesliga,first_tier,40,Germany,L1,europa,https://www.transfermarkt.co.uk/bundesliga/sta...
1,DFB,dfb-pokal,domestic_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfb-pokal/star...
2,DFL,dfl-supercup,domestic_super_cup,40,Germany,L1,europa,https://www.transfermarkt.co.uk/dfl-supercup/s...
3,NL1,eredivisie,first_tier,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/eredivisie/sta...
4,NLP,toto-knvb-beker,domestic_cup,122,Netherlands,NL1,europa,https://www.transfermarkt.co.uk/toto-knvb-beke...

In [6]:
games_df = pd.read_csv(games)
games_df.head()

,game_id,competition_code,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,away_club_position,stadium,attendance,url
0,2581147,L1,2015,1. Matchday,2015-08-14,27,41,5,0,1.0,18.0,Allianz Arena,75024.0,https://www.transfermarkt.co.uk/bayern-munich_...
1,2576512,DFL,2015,Final,2015-08-01,82,27,6,5,NaN,NaN,Volkswagen Arena,30000.0,https://www.transfermarkt.co.uk/spielbericht/i...
2,2581181,L1,2015,2. Matchday,2015-08-22,533,27,1,2,16.0,2.0,PreZero Arena,30150.0,https://www.transfermarkt.co.uk/tsg-1899-hoffe...
3,2581179,L1,2015,2. Matchday,2015-08-22,42,15,0,1,13.0,3.0,HDI-Arena,39100.0,https://www.transfermarkt.co.uk/hannover-96_ba...
4,2581178,L1,2015,2. Matchday,2015-08-22,3,82,1,1,5.0,6.0,RheinEnergieStadion,46000.0,https://www.transfermarkt.co.uk/1-fc-koln_vfl-...

In [7]:
players_df = pd.read_csv(players)
players_df.head()

,player_id,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,height_in_cm,url
0,257767,4795,aloy-ihenacho,Aloy Ihenacho,Nigeria,Nigeria,1995-07-21,Attack,Centre-Forward,Left,182,https://www.transfermarkt.co.uk/aloy-ihenacho/...
1,320889,4795,thomas-blomeyer,Thomas Blomeyer,Germany,Germany,1996-04-24,Defender,Centre-Back,Both,191,https://www.transfermarkt.co.uk/thomas-blomeye...
2,42318,4795,konstantin-engel,Konstantin Engel,UdSSR,Kazakhstan,1988-07-27,Defender,Centre-Back,Right,179,https://www.transfermarkt.co.uk/konstantin-eng...
3,94598,4795,stefan-wannenwetsch,Stefan Wannenwetsch,Germany,Germany,NaN,Midfield,Defensive Midfield,Right,177,https://www.transfermarkt.co.uk/stefan-wannenw...
4,381921,6994,ivan-komlev,Ivan Komlev,NaN,Ukraine,1994-07-22,Defender,Centre-Back,NaN,181,https://www.transfermarkt.co.uk/ivan-komlev/pr...

In [8]:
df_list = [appearances_df, clubs_df, competitions_df, games_df, players_df]
name_list = ["appearances_df", "clubs_df", "competitions_df", "games_df", "players_df"]
for i in range(len(name_list)):
    print(f'{name_list[i].upper()} has columns with NaN values:')
    print(df_list[i].isna().sum())
    print(" ")

APPEARANCES_DF has columns with NaN values:
player_id         0
game_id           0
appearance_id     0
competition_id    0
player_club_id    0
goals             0
assists           0
minutes_played    0
yellow_cards      0
red_cards         0
dtype: int64

CLUBS_DF has columns with NaN values:
club_id                     0
name                        0
pretty_name                 0
domestic_competition_id     0
total_market_value         18
squad_size                  0
average_age                 0
foreigners_number           0
foreigners_percentage      27
national_team_players       0
stadium_name                0
stadium_seats               0
net_transfer_record         0
coach_name                  0
url                         0
dtype: int64

COMPETITIONS_DF has columns with NaN values:
competition_id          0
name                    0
type                    0
country_id              0
country_name            7
domestic_league_code    7
confederation           0
url                     0
dtype: int64

GAMES_DF has columns with NaN values:
game_id                   0
competition_code          0
season                    0
round                     0
date                      0
home_club_id              0
away_club_id              0
home_club_goals           0
away_club_goals           0
home_club_position    10429
away_club_position    10430
stadium                  93
attendance             7514
url                       0
dtype: int64

PLAYERS_DF has columns with NaN values:
player_id                    0
current_club_id              0
name                         0
pretty_name                  0
country_of_birth          1502
country_of_citizenship       0
date_of_birth               21
position                     0
sub_position                 0
foot                      1661
height_in_cm                 0
url                          0
dtype: int64

In [9]:
players_df.describe()

           player_id  current_club_id  height_in_cm
count   20626.000000     20626.000000  20626.000000
mean   289222.910889      4145.085378    172.197227
std    203292.082994      9223.325976     42.135029
min        10.000000         3.000000      0.000000
25%    111058.750000       383.000000    176.000000
50%    265527.500000      1050.000000    182.000000
75%    422451.250000      2999.000000    187.000000
max    949337.000000     61825.000000    206.000000

In [10]:
players_df.dtypes

player_id                  int64
current_club_id            int64
name                      object
pretty_name               object
country_of_birth          object
country_of_citizenship    object
date_of_birth             object
position                  object
sub_position              object
foot                      object
height_in_cm               int64
url                       object
dtype: object

In [11]:
# Dropping NaN values from columns of interest (Appereances, Clubs and Players)
players_df.dropna()
appearances_df.dropna()
clubs_df.dropna()
games_df #2021 filtro
# Print new shape
print(appearances_df.shape)
print(players_df.shape)
print(clubs_df.shape)

(820242, 10)
(20626, 12)
(364, 15)

In [13]:
# 2018 games are 5641
games_df[games_df["season"] == 2018].count()

game_id               5641
competition_code      5641
season                5641
round                 5641
date                  5641
home_club_id          5641
away_club_id          5641
home_club_goals       5641
away_club_goals       5641
home_club_position    3986
away_club_position    3986
stadium               5631
attendance            5305
url                   5641
dtype: int64

In [19]:
# Adding new dataset in order to obtain the market value of each players
top250_df = pd.read_csv(top250)
top250_df

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee
0,Lu√≠s Figo,Right Winger,27,FC Barcelona,LaLiga,Real Madrid,LaLiga,2000-2001,NaN,60000000
1,Hern√°n Crespo,Centre-Forward,25,Parma,Serie A,Lazio,Serie A,2000-2001,NaN,56810000
2,Marc Overmars,Left Winger,27,Arsenal,Premier League,FC Barcelona,LaLiga,2000-2001,NaN,40000000
3,Gabriel Batistuta,Centre-Forward,31,Fiorentina,Serie A,AS Roma,Serie A,2000-2001,NaN,36150000
4,Nicolas Anelka,Centre-Forward,21,Real Madrid,LaLiga,Paris SG,Ligue 1,2000-2001,NaN,34500000
...,...,...,...,...,...,...,...,...,...,...
4695,Jasmin Kurtic,Attacking Midfield,29,Atalanta,Serie A,SPAL,Serie A,2018-2019,5000000.0,4800000
4696,Tch√™ Tch√™,Central Midfield,25,Palmeiras,S√©rie A,Dynamo Kyiv,Premier Liga,2018-2019,3000000.0,4800000
4697,Silvan Widmer,Right-Back,25,Udinese Calcio,Serie A,FC Basel,Super League,2018-2019,8500000.0,4500000
4698,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000
4699,Kyle Bartley,Centre-Back,27,Swansea,Championship,West Brom,Championship,2018-2019,3500000.0,4500000

In [22]:
top250_df.dtypes

Name             object
Position         object
Age               int64
Team_from        object
League_from      object
Team_to          object
League_to        object
Season           object
Market_value    float64
Transfer_fee      int64
dtype: object

In [33]:
top250_df.isnull().sum()

Name               0
Position           0
Age                0
Team_from          0
League_from        0
Team_to            0
League_to          0
Season             0
Market_value    1260
Transfer_fee       0
dtype: int64

In [37]:
# Dropping NaN values
top250_NaN = top250_df.dropna()
top250_NaN

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee
999,Carlos T√©vez,Second Striker,20,Boca Juniors,Argentina,Corinthians,S√©rie A,2004-2005,15000000.0,15000000
1001,Valeri Bojinov,Centre-Forward,18,Lecce,Serie A,Fiorentina,Serie A,2004-2005,13000000.0,14000000
1004,Jiri Jarosik,Centre-Back,27,CSKA Moscow,Premier Liga,Chelsea,Premier League,2004-2005,5000000.0,12000000
1009,Jean-Alain Boumsong,Centre-Back,25,Rangers,Premiership,Newcastle,Premier League,2004-2005,8500000.0,11300000
1011,Nicolas Anelka,Centre-Forward,25,Man City,Premier League,Fenerbahce,S√ºper Lig,2004-2005,15000000.0,10700000
...,...,...,...,...,...,...,...,...,...,...
4695,Jasmin Kurtic,Attacking Midfield,29,Atalanta,Serie A,SPAL,Serie A,2018-2019,5000000.0,4800000
4696,Tch√™ Tch√™,Central Midfield,25,Palmeiras,S√©rie A,Dynamo Kyiv,Premier Liga,2018-2019,3000000.0,4800000
4697,Silvan Widmer,Right-Back,25,Udinese Calcio,Serie A,FC Basel,Super League,2018-2019,8500000.0,4500000
4698,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000
4699,Kyle Bartley,Centre-Back,27,Swansea,Championship,West Brom,Championship,2018-2019,3500000.0,4500000

In [39]:
# Counting athletes per season
top250_NaN["Season"].value_counts()

2016-2017    249
2011-2012    248
2015-2016    248
2013-2014    248
2009-2010    247
2012-2013    246
2014-2015    245
2008-2009    243
2018-2019    242
2010-2011    241
2017-2018    241
2007-2008    235
2006-2007    229
2005-2006    219
2004-2005     59
Name: Season, dtype: int64

In [41]:
# 241 athletes in the 2017-2018 season
top250_NaN[top250_NaN['Season'] == "2017-2018"]

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee
4211,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000
4212,Philippe Coutinho,Attacking Midfield,25,Liverpool,Premier League,FC Barcelona,LaLiga,2017-2018,90000000.0,125000000
4213,Ousmane Demb√©l√©,Right Winger,20,Bor. Dortmund,1.Bundesliga,FC Barcelona,LaLiga,2017-2018,33000000.0,115000000
4214,Romelu Lukaku,Centre-Forward,24,Everton,Premier League,Man Utd,Premier League,2017-2018,50000000.0,84700000
4215,Virgil van Dijk,Centre-Back,26,Southampton,Premier League,Liverpool,Premier League,2017-2018,30000000.0,78800000
...,...,...,...,...,...,...,...,...,...,...
4450,Diego Llorente,Centre-Back,23,Real Madrid,LaLiga,Real Sociedad,LaLiga,2017-2018,7500000.0,7000000
4451,Clinton N'Jie,Centre-Forward,23,Spurs,Premier League,Marseille,Ligue 1,2017-2018,7000000.0,7000000
4452,Marcelo,Centre-Back,30,Besiktas,S√ºper Lig,Olympique Lyon,Ligue 1,2017-2018,6500000.0,7000000
4453,Jorge Mer√©,Centre-Back,20,Sporting Gij√≥n,LaLiga2,1. FC K√∂ln,1.Bundesliga,2017-2018,6000000.0,7000000
4454,V√≠ctor Camarasa,Central Midfield,23,Levante UD,LaLiga,Real Betis,LaLiga,2017-2018,5000000.0,7000000

In [40]:
# 242 athletes in the 2018-2019 season
top250_NaN[top250_NaN['Season'] == "2018-2019"]

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee
4455,Kylian Mbapp√©,Right Winger,19,Monaco,Ligue 1,Paris SG,Ligue 1,2018-2019,120000000.0,135000000
4456,Cristiano Ronaldo,Centre-Forward,33,Real Madrid,LaLiga,Juventus,Serie A,2018-2019,100000000.0,117000000
4457,Thomas Lemar,Left Winger,22,Monaco,Ligue 1,Atl√©tico Madrid,LaLiga,2018-2019,65000000.0,70000000
4458,Riyad Mahrez,Right Winger,27,Leicester,Premier League,Man City,Premier League,2018-2019,50000000.0,67800000
4459,Alisson,Goalkeeper,25,AS Roma,Serie A,Liverpool,Premier League,2018-2019,60000000.0,62500000
...,...,...,...,...,...,...,...,...,...,...
4695,Jasmin Kurtic,Attacking Midfield,29,Atalanta,Serie A,SPAL,Serie A,2018-2019,5000000.0,4800000
4696,Tch√™ Tch√™,Central Midfield,25,Palmeiras,S√©rie A,Dynamo Kyiv,Premier Liga,2018-2019,3000000.0,4800000
4697,Silvan Widmer,Right-Back,25,Udinese Calcio,Serie A,FC Basel,Super League,2018-2019,8500000.0,4500000
4698,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000
4699,Kyle Bartley,Centre-Back,27,Swansea,Championship,West Brom,Championship,2018-2019,3500000.0,4500000

In [57]:
# 483 in both seasons
top250_2018 = top250_NaN[(top250_NaN['Season'] == "2017-2018") | (top250_NaN['Season'] == "2018-2019")]
top250_2018

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee
4211,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000
4212,Philippe Coutinho,Attacking Midfield,25,Liverpool,Premier League,FC Barcelona,LaLiga,2017-2018,90000000.0,125000000
4213,Ousmane Demb√©l√©,Right Winger,20,Bor. Dortmund,1.Bundesliga,FC Barcelona,LaLiga,2017-2018,33000000.0,115000000
4214,Romelu Lukaku,Centre-Forward,24,Everton,Premier League,Man Utd,Premier League,2017-2018,50000000.0,84700000
4215,Virgil van Dijk,Centre-Back,26,Southampton,Premier League,Liverpool,Premier League,2017-2018,30000000.0,78800000
...,...,...,...,...,...,...,...,...,...,...
4695,Jasmin Kurtic,Attacking Midfield,29,Atalanta,Serie A,SPAL,Serie A,2018-2019,5000000.0,4800000
4696,Tch√™ Tch√™,Central Midfield,25,Palmeiras,S√©rie A,Dynamo Kyiv,Premier Liga,2018-2019,3000000.0,4800000
4697,Silvan Widmer,Right-Back,25,Udinese Calcio,Serie A,FC Basel,Super League,2018-2019,8500000.0,4500000
4698,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000
4699,Kyle Bartley,Centre-Back,27,Swansea,Championship,West Brom,Championship,2018-2019,3500000.0,4500000

In [135]:
# Merging games_df and appearances_df in order and filtering by 2018 season
df_2018 = pd.merge(games_df, appearances_df, how="inner", on=["game_id", "game_id"])
df_2018 = df_2018.loc[df_2018["season"] == 2018]
df_2018

,game_id,competition_code,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,url,player_id,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards
391397,3055009,NLSC,2018,Final,2018-08-04,383,234,6,7,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,287579,3055009_287579,NLSC,234,0,0,28,0,0
391398,3055009,NLSC,2018,Final,2018-08-04,383,234,6,7,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,104223,3055009_104223,NLSC,234,1,0,90,0,0
391399,3055009,NLSC,2018,Final,2018-08-04,383,234,6,7,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,315121,3055009_315121,NLSC,234,0,0,90,0,0
391400,3055009,NLSC,2018,Final,2018-08-04,383,234,6,7,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,182581,3055009_182581,NLSC,234,1,0,90,0,0
391401,3055009,NLSC,2018,Final,2018-08-04,383,234,6,7,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,369319,3055009_369319,NLSC,234,1,0,6,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
636021,3223001,ELQ,2018,Second Round 1st leg,2019-07-25,10695,3426,2,0,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,156116,3223001_156116,ELQ,3426,0,0,90,0,0
636022,3223001,ELQ,2018,Second Round 1st leg,2019-07-25,10695,3426,2,0,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,73662,3223001_73662,ELQ,3426,0,0,45,0,0
636023,3223001,ELQ,2018,Second Round 1st leg,2019-07-25,10695,3426,2,0,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,77855,3223001_77855,ELQ,3426,0,0,21,0,0
636024,3223001,ELQ,2018,Second Round 1st leg,2019-07-25,10695,3426,2,0,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,390664,3223001_390664,ELQ,3426,0,0,45,0,0
636025,3223001,ELQ,2018,Second Round 1st leg,2019-07-25,10695,3426,2,0,NaN,...,https://www.transfermarkt.co.uk/spielbericht/i...,345595,3223001_345595,ELQ,3426,0,0,90,0,0

In [119]:
len(df_2018["player_id"].unique())

7088

In [138]:
# Merging players_df and df_2018 
players_2018 = pd.merge(players_df, df_2018, how="inner", on=["player_id", "player_id"])
players_2018

,player_id,current_club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,...,attendance,url_y,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards
0,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,50000.0,https://www.transfermarkt.co.uk/fortuna-dussel...,3058728_39426,L1,42,1,0,20,0,0
1,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,30400.0,https://www.transfermarkt.co.uk/hannover-96_1-...,3058699_39426,L1,42,0,0,45,0,0
2,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,38916.0,https://www.transfermarkt.co.uk/hertha-bsc_han...,3058688_39426,L1,42,0,0,17,0,0
3,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,40200.0,https://www.transfermarkt.co.uk/hannover-96_bo...,3058681_39426,L1,42,0,0,90,0,0
4,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,23512.0,https://www.transfermarkt.co.uk/vfl-wolfsburg_...,3058674_39426,L1,42,0,0,70,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129521,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,41257.0,https://www.transfermarkt.co.uk/borussia-monch...,3058454_7161,L1,18,0,0,90,0,0
129522,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,48755.0,https://www.transfermarkt.co.uk/spielbericht/i...,3096458_7161,DFB,18,0,0,75,0,0
129523,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,54022.0,https://www.transfermarkt.co.uk/borussia-monch...,3058436_7161,L1,18,0,1,90,0,0
129524,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,29580.0,https://www.transfermarkt.co.uk/fc-augsburg_bo...,3058430_7161,L1,18,0,0,90,0,0
129525,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,53087.0,https://www.transfermarkt.co.uk/borussia-monch...,3058408_7161,L1,18,1,0,90,0,0

In [145]:
players_2018.rename(columns={"pretty_name": "Name"}, inplace=True)
players_2018

,player_id,current_club_id,name,Name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,foot,...,attendance,url_y,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards
0,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,50000.0,https://www.transfermarkt.co.uk/fortuna-dussel...,3058728_39426,L1,42,1,0,20,0,0
1,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,30400.0,https://www.transfermarkt.co.uk/hannover-96_1-...,3058699_39426,L1,42,0,0,45,0,0
2,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,38916.0,https://www.transfermarkt.co.uk/hertha-bsc_han...,3058688_39426,L1,42,0,0,17,0,0
3,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,40200.0,https://www.transfermarkt.co.uk/hannover-96_bo...,3058681_39426,L1,42,0,0,90,0,0
4,39426,42,nicolai-muller,Nicolai Muller,Germany,Germany,1987-09-25,Midfield,Attacking Midfield,Right,...,23512.0,https://www.transfermarkt.co.uk/vfl-wolfsburg_...,3058674_39426,L1,42,0,0,70,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129521,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,41257.0,https://www.transfermarkt.co.uk/borussia-monch...,3058454_7161,L1,18,0,0,90,0,0
129522,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,48755.0,https://www.transfermarkt.co.uk/spielbericht/i...,3096458_7161,DFB,18,0,0,75,0,0
129523,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,54022.0,https://www.transfermarkt.co.uk/borussia-monch...,3058436_7161,L1,18,0,1,90,0,0
129524,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,29580.0,https://www.transfermarkt.co.uk/fc-augsburg_bo...,3058430_7161,L1,18,0,0,90,0,0
129525,7161,18,jonas-hofmann,Jonas Hofmann,Germany,Germany,1992-07-14,Attack,Right Winger,Right,...,53087.0,https://www.transfermarkt.co.uk/borussia-monch...,3058408_7161,L1,18,1,0,90,0,0

In [146]:
market_value_2018 = pd.merge(top250_2018, players_2018, how="inner", on=["Name", "Name"])
market_value_2018

,Name,Position,Age,Team_from,League_from,Team_to,League_to,Season,Market_value,Transfer_fee,...,attendance,url_y,appearance_id,competition_id,player_club_id,goals,assists,minutes_played,yellow_cards,red_cards
0,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000,...,33138.0,https://www.transfermarkt.co.uk/ogc-nice_paris...,3047536_68290,FR1,583,2,0,90,0,0
1,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000,...,14728.0,https://www.transfermarkt.co.uk/sco-angers_par...,3047871_68290,FR1,583,1,1,90,0,0
2,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000,...,47283.0,https://www.transfermarkt.co.uk/paris-saint-ge...,3047866_68290,FR1,583,1,0,90,0,0
3,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000,...,20477.0,https://www.transfermarkt.co.uk/montpellier-hs...,3047856_68290,FR1,583,0,0,90,0,0
4,Neymar,Left Winger,25,FC Barcelona,LaLiga,Paris SG,Ligue 1,2017-2018,100000000.0,222000000,...,43581.0,https://www.transfermarkt.co.uk/paris-saint-ge...,3047846_68290,FR1,583,0,0,45,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9304,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000,...,39100.0,https://www.transfermarkt.co.uk/sv-werder-brem...,3058455_108650,L1,86,0,0,90,0,0
9305,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000,...,42100.0,https://www.transfermarkt.co.uk/spielbericht/i...,3174557_108650,DFB,86,1,0,90,0,0
9306,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000,...,42100.0,https://www.transfermarkt.co.uk/sv-werder-brem...,3058437_108650,L1,86,0,0,88,0,0
9307,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000,...,50000.0,https://www.transfermarkt.co.uk/eintracht-fran...,3058429_108650,L1,86,1,0,90,0,0
9308,Yuya Osako,Second Striker,28,1. FC K√∂ln,2.Bundesliga,Werder Bremen,1.Bundesliga,2018-2019,4500000.0,4500000,...,42100.0,https://www.transfermarkt.co.uk/sv-werder-brem...,3058410_108650,L1,86,0,0,90,0,0

In [148]:
len(market_value_2018["Name"].unique())

307

In [139]:
# Get the total unique players in 2018
print(len(players_2018["pretty_name"].unique())) #20,290
unique_players_2018 = players_2018["pretty_name"].unique()

7024

In [121]:
unique_players_2018

array(['Nicolai Muller', 'Julian Korb', 'Pirmin Schwegler', ...,
       'Marcel Halstenberg', 'Philipp Tschauner', 'Jonas Hofmann'],
      dtype=object)

In [122]:
if "Aloy Ihenacho" in unique_players_2018:
    print("Yes")
else:
    print("No")

No

In [64]:
# Unique players in both lists
list_player_names = players_df["pretty_name"].tolist()

counter = 0
for name in list_player_names:
    if name in top250_2018["Name"].tolist():
        counter += 1
    else:
        counter = counter
print(counter)

365

In [102]:
len(list_player_names)

20626

In [131]:
# Unique players in 2018 in both lists
x = 0
for name in unique_players_2018:
    if name in names:
        x += 1
    else:
        x = x
x

307