## Connection from Heroku Database to Python

In [1]:
import psycopg2
import pandas as pd

from getpass import getpass
password = getpass('Enter database password')

connection = psycopg2.connect(user="azcaqpdjrciaow",
                                  password=password,
                                  host="ec2-34-226-18-183.compute-1.amazonaws.com",
                                  port="5432",
                                  database="d7m85rf8c5rhv5")
cursor = connection.cursor()
postgreSQL_select_Query = "select * from player_market_values"

cursor.execute(postgreSQL_select_Query)
print("Loading data from Heroku")

data = cursor.fetchall()
df = pd.DataFrame(data, columns=['player_id', 'player_name', 'age', 'club_id', \
                                                    'team_from', 'league_from', 'team_to', 'country_of_birth', \
                                                    'country_of_citizenship', 'player_position', 'games', 'goals', \
                                                    'assists', 'hours_played', 'yellow_cards', 'red_cards', 'transfer_fee', \
                                                    'market_value', 'club_market_value', 'season'])
df

Enter database password········
Loading data from Heroku

,player_id,player_name,age,club_id,team_from,league_from,team_to,country_of_birth,country_of_citizenship,player_position,games,goals,assists,hours_played,yellow_cards,red_cards,transfer_fee,market_value,club_market_value,season
0,68290,Neymar,25,583,FC Barcelona,LaLiga,Paris SG,Brazil,Brazil,Attack,27,25,16,40.4500,8,0,222000000,100000000,891180000,2017
1,8198,Cristiano Ronaldo,33,985,Real Madrid,LaLiga,Juventus,Portugal,Portugal,Attack,43,28,10,60.7667,4,1,117000000,100000000,816530000,2018
2,80444,Philippe Coutinho,25,131,Liverpool,Premier League,FC Barcelona,Brazil,Brazil,Midfield,42,21,15,49.8833,1,0,125000000,90000000,604800000,2017
3,122153,Paul Pogba,23,985,Juventus,Serie A,Man Utd,France,France,Midfield,49,9,5,70.5500,10,0,105000000,70000000,816530000,2016
4,205562,Thomas Lemar,22,13,Monaco,Ligue 1,Atlético Madrid,Guadeloupe,France,Midfield,43,3,6,43.5333,5,0,70000000,65000000,671310000,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
705,345590,Jens Odgaard,19,235,Inter,Serie A,Sassuolo,Denmark,Denmark,Attack,1,0,0,0.2500,0,0,5000000,800000,9050000,2018
706,310458,Giangiacomo Magnani,22,276,Juventus,Serie A,Sassuolo,Italy,Italy,Defender,22,0,1,29.7333,3,0,5000000,600000,98420000,2018
707,310458,Giangiacomo Magnani,22,276,Perugia,Serie B,Juventus,Italy,Italy,Defender,22,0,1,29.7333,3,0,5000000,600000,98420000,2018
708,291422,Lys Mousset,20,350,AC Le Havre,Ligue 2,Bournemouth,France,France,Attack,13,0,0,5.8667,0,0,6500000,400000,113040000,2016
709,341317,Oliver Burke,19,350,Nottm Forest,Championship,RB Leipzig,Scotland,Scotland,Attack,27,1,3,12.2833,1,0,15200000,250000,113040000,2016